### ISSUE TITLE
Cant find some libraries

### ISSUE THREAD

**Issue by nazib** [adalca/patchRegistration#1]
Hi 
I wanted to use this registration for my research. But some libraries mentioned in setup.m file are missing. 
Missing libs are : 
1. https://github.com/adalca/mgt
2.  https://github.com/adalca/mmit
3.  https://github.com/adalca/mivt
Have any idea how to get them?

regards

**Comment by adalca** [comment]
hi @nazib, 
all of those were put together into https://github.com/adalca/matlib, so you only need to import this one library now instead of those three.

I've made the change in the `setup.m`

Thanks for your interest!

**Comment by nazib** [comment]
thanks a lot @adalca

**Comment by nazib** [comment]
Hi @adalca 
Thanks for your libraries. Just a simple question, do you know any python/matlab library that can extract  overlapping 3D patches  from MRI images?

**Comment by adalca** [comment]
Hi @nazib 

I wrote some libraries for this in both languages. 

For matlab, see [patchlib](https://github.com/adalca/patchlib), perhaps function [vol2lib](https://github.com/adalca/patchlib/blob/master/src/%2Bpatchlib/vol2lib.m), it has a ton of settings including overlapping. 

For python, see [pytools patchlib](https://github.com/adalca/pytools-lib/blob/master/pytools/patchlib.py), which has less functionality overall, but `patch_gen()` should work for you.

There's probably other libraries out there, but I'm familiar with these :)

**Comment by nazib** [comment]
Hi @adalca 
thanks for your information. It works.  Is there any other function that combines the pathes and generate full resolution image?

**Comment by adalca** [comment]
Yup -- look for `quilt` function in either library
